4th exercise: adding lint to makefile

diff --git a/4-ci-pipeline/Makefile b/4-ci-pipeline/Makefile
--- a/4-ci-pipeline/Makefile
+++ b/4-ci-pipeline/Makefile
@@ -5,6 +5,12 @@ run_tests: run_prerequisites
 	python3 -m pytest -v && \
 	rm -r .pytest_cache __pycache__
 
+run_lint: run_prerequisites
+	python3 -m pylint -E app/*.py && \
+	if [ $$? -eq 0 ]; then \
+		echo "No errors in the code!"; \
+	fi
+
 run_prerequisites:
 	touch app/.env
 	echo "DATABASE_URI=sqlite:///data.db" > app/.env
